INSERT INTO T_SHOP (SHOP_ID, SHOP_NAME, PASSWORD, AMOUNT_REDEEM) values ('s001', 'SHOP1', 'password', 50);

INSERT INTO T_PUSH_NOTIFICATION (SHOP_ID, CHANNEL_ID, USER_ID, MESSAGE) values ('s001', 'CID', 'UID', 'HI There1');
INSERT INTO T_PUSH_NOTIFICATION (SHOP_ID, CHANNEL_ID, USER_ID, MESSAGE) values ('s001', 'CID', 'UID', 'HI There2');
INSERT INTO T_PUSH_NOTIFICATION (SHOP_ID, CHANNEL_ID, USER_ID, MESSAGE) values ('s001', 'CID', 'UID', 'HI There3');
INSERT INTO T_PUSH_NOTIFICATION (SHOP_ID, CHANNEL_ID, USER_ID, MESSAGE) values ('s001', 'CID', 'UID', 'HI There4');
INSERT INTO T_PUSH_NOTIFICATION (SHOP_ID, CHANNEL_ID, USER_ID, MESSAGE) values ('s001', 'CID', 'UID', 'HI There5');
INSERT INTO T_PUSH_NOTIFICATION (SHOP_ID, CHANNEL_ID, USER_ID, MESSAGE) values ('s001', 'CID', 'UID', 'HI There5');