INSERT INTO T_MOBILE_AUTH (MOBILE, AUTH_CODE, USER_TYPE) values ('s001', '45', 'SHOP');
INSERT INTO T_MOBILE_AUTH (MOBILE, AUTH_CODE, USER_TYPE) values ('s001', '46', 'SHOP');
INSERT INTO T_MOBILE_AUTH (MOBILE, AUTH_CODE, USER_TYPE) values ('s001', '47', 'SHOP');
