INSERT INTO T_SHOP (SHOP_ID, SHOP_NAME, PASSWORD, AMOUNT_REDEEM) values ('s001', 'SHOP1', 'password', 50);
INSERT INTO T_SHOP (SHOP_ID, SHOP_NAME, PASSWORD, AMOUNT_REDEEM) values ('s002', 'SHOP2', 'password', 50);
INSERT INTO T_SHOP (SHOP_ID, SHOP_NAME, PASSWORD, AMOUNT_REDEEM) values ('s003', 'SHOP3', 'password', 50);

INSERT INTO T_CUSTOMER (CUSTOMER_ID, PASSWORD) values ('c001', 'Password');
INSERT INTO T_CUSTOMER (CUSTOMER_ID, PASSWORD, USER_ID, CHANNEL_ID) values ('c002', 'Password', 'UID', 'CID');

INSERT INTO T_TRANSACTION_SUMMARY (SHOP_ID, CUSTOMER_ID, TOTAL_CUPS, TOTAL_AMOUNT, TOTAL_CUPS_REDEEMED, TOTAL_AMOUNT_REDEEMED) 
VALUES ('s003', 'c002', 0, 50, 0, 0);
